# Generated by Django 5.0.3 on 2024-05-24 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_subtask_remove_task_subtasks_task_subtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='subtask',
        ),
        migrations.DeleteModel(
            name='Subtask',
        ),
    ]
