# Generated by Django 5.0.3 on 2024-03-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_taskhistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistory',
            name='category',
            field=models.CharField(default='Others', max_length=255),
        ),
    ]
