# Generated by Django 5.0.3 on 2024-03-21 14:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_alter_taskhistory_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskHistory',
            new_name='CompletedTask',
        ),
        migrations.AlterModelOptions(
            name='completedtask',
            options={'verbose_name_plural': 'Completed Task'},
        ),
    ]
